# Generated by Django 6.0.3 on 2026-04-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('risk_level', models.CharField(max_length=20)),
                ('trigger_text', models.TextField(blank=True)),
                ('action_taken', models.TextField(blank=True)),
                ('acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(blank=True, max_length=100)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('energy_level', models.CharField(blank=True, max_length=50)),
                ('query', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('reasoning', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('build', 'Build'), ('break', 'Break')], max_length=10)),
                ('target_count', models.IntegerField(default=1)),
                ('current_count', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('last_reset_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('alert_tier', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Identity', 'Identity'), ('Family', 'Family'), ('Medication', 'Medication'), ('Preference', 'Preference'), ('Other', 'Other')], max_length=50)),
                ('fact', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=5)),
                ('category', models.CharField(choices=[('Medication', 'Medication'), ('Nutrition', 'Nutrition'), ('Social', 'Social'), ('Physical Activity', 'Physical Activity'), ('Other', 'Other')], max_length=50)),
                ('alert_tier', models.IntegerField(default=1)),
                ('recurrence', models.CharField(default='daily', max_length=50)),
                ('last_triggered', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.CharField(blank=True, max_length=10, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('alert_tier', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
